version: '3'
services:
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kuma_test
      MYSQL_USER: kuma
      MYSQL_PASSWORD: kuma
    ports:
      - "3306:3306"
    volumes:
      - ./test/init.sql:/docker-entrypoint-initdb.d/init.sql